name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  linux-build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cc:
          - gcc-14
          - clang-19
        build-type: [ Release, Debug ]
    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo apt-get update
        sudo apt-get install -y ${{matrix.cc}} libwayland-dev
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
          -DCMAKE_C_COMPILER=${{matrix.cc}} \
          -DMIMAS_BUILD_WAYLAND=ON
    - name: Build
      run: cmake --build ${{github.workspace}}/build

  windows-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Release, Debug ]
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build `
          -DCMAKE_BUILD_TYPE=${{matrix.build-type}} `
          -DMIMAS_BUILD_WINDOWS=ON
    - name: Build
      run: cmake --build ${{github.workspace}}/build
